# Override file for scaling and additional configurations
services:
  # Horizontal scaling configuration
  backend:
    deploy:
      replicas: 3  # Scale to 3 replicas
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1.5'
          memory: 768M
        reservations:
          cpus: '0.75'
          memory: 384M

  # Load balancer configuration with health checks
  nginx:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Enhanced monitoring stack
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '0.75'
          memory: 1G

  grafana:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 384M