server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-containers
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      # Extract container ID from file path
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[a-f0-9]{64})/.*'
          source: filename
      
      # Parse JSON log format
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs: attrs
      
      # Extract container name from attrs.tag if available
      - json:
          expressions:
            tag:
          source: attrs
      
      # Try to extract container name from tag field
      - regex:
          expression: '(?P<container_name>[a-zA-Z0-9][a-zA-Z0-9_.-]*)'
          source: tag
      
      # Set timestamp
      - timestamp:
          format: RFC3339Nano
          source: time
      
      # Add labels
      - labels:
          stream:
          container_id:
          container_name:
      
      # Output the log message
      - output:
          source: output