server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs: attrs

      # Extract container ID from filename using a simpler approach
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id_full>[a-f0-9]{64})/.*'
          source: filename

      # Get short container ID (first 12 chars)
      - template:
          source: container_id
          template: '{{ .container_id_full | substr 0 12 }}'

      # Manually set container names based on container ID
      - template:
          source: container_name
          template: |
            {{ if eq .container_id "1335677d667d" }}cadvisor
            {{ else if eq .container_id "b2f40d7c1b86" }}nginx
            {{ else if eq .container_id "8c4ae4164e05" }}grafana
            {{ else if eq .container_id "e873776e022d" }}promtail
            {{ else if eq .container_id "2629aed3ca7d" }}loki
            {{ else if eq .container_id "66bb1f376a56" }}prometheus
            {{ else if eq .container_id "27dd2c5eff20" }}node-exporter
            {{ else if eq .container_id "9af8d570f245" }}backend
            {{ else if eq .container_id "2666317c91ef" }}jaeger
            {{ else }}unknown-{{ .container_id }}{{ end }}

      - timestamp:
          format: RFC3339Nano
          source: time

      - labels:
          stream:
          container_id:
          container_name:

      - output:
          source: output