server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs: attrs
      - json:
          expressions:
            tag:
          source: attrs
      - template:
          source: tag
          template: '{{ .tag }}'
      - regex:
          expression: '/(?P<container_name>[^/]+)$'
          source: tag
      - labels:
          stream:
          container_name:
      - timestamp:
          format: RFC3339Nano
          source: time
      - output:
          source: output